include:
  - board: nice_nano_v2
    shield: klor_left nice_view_adapter  nice_view_custom #custom shield
  - board: nice_nano_v2
    shield: klor_right nice_view_adapter nice_view_custom #custom shield
